[files]
extend-exclude = ["typos.toml", "typos_known", "typos_new"]

[default.extend-words]
absic = "basic"
adnvanced = "advanced"
agnet = "agent"
aleready = "already"
alrge = "large"
atuhkey = "authkey"
axists = "exists"
budle = "bundle"
clsuter = "cluster"
cocorync = "corosync"
commes = "comes"
corosnyc = "corosync"
decsribes = "describes"
depraceted = "deprecated"
foce = "force"
iddle = "idle"
inlfuences = "influences"
medatada = "metadata"
monitro = "monitor"
muttualy = "mutually"
operatin = "operation"
oudside = "outside"
pacakamer = "pacemaker"
pririty = "priority"
quourm = "quorum"
relevatnt = "relevant"
resrource = "resource"
restarless = "restartless"
selimited = "delimited"
sotnith = "stonith"
startdards = "standards"
stontih = "stonith"
timedouted = "timeouted"
ugrade = "upgrade"
understore = "underscore"
valeus = "values"
webbrick = "webrick"
wpecified = "specified"
proprties = "properties"
